export const DEFAULT_PASSWORD = 'password'
export const SALT_ROUNDS = 10
export const countries = {
    US: 'US',
    CA: 'Canada',
    GB: 'UK',
    AU: 'Australia',
    FR: 'France',
    DE: 'Germany',
    JP: 'Japan',
    CN: 'China',
    IN: 'India',
    BR: 'Brazil',
    RU: 'Russia',
    IT: 'Italy',
    ES: 'Spain',
    MX: 'Mexico',
    KR: 'South Korea',
    NL: 'Netherlands',
    SE: 'Sweden',
    NG: 'Nigeria',
    AR: 'Argentina',
    SG: 'Singapore',
    PH: 'Philippines',
    BE: 'Belgium',
    PT: 'Portugal',
    DK: 'Denmark',
    FI: 'Finland',
    IE: 'Ireland',
    ZA: 'South Africa',
    KE: 'Kenya',
    GH: 'Ghana',
    MA: 'Morocco',
    CO: 'Colombia',
    CL: 'Chile',
}
