export const DEFAULT_PASSWORD = 'password'
export const SALT_ROUNDS = 10
export const FRIEND_RATIO = 0.5 // the highest number of friends a person can have is (around) 0.5 of the total number of users
export const GROUP_SIZE_RATIO = 0.5
export const START_YEAR = 2021
export const END_YEAR = 2023
export const countries = [
    'US',
    'Canada',
    'UK',
    'Australia',
    'France',
    'Germany',
    'Japan',
    'China',
    'India',
    'Brazil',
    'Russia',
    'Italy',
    'Spain',
    'Mexico',
    'South Korea',
    'Netherlands',
    'Sweden',
    'Nigeria',
    'Argentina',
    'Singapore',
    'Philippines',
    'Belgium',
    'Portugal',
    'Denmark',
    'Finland',
    'Ireland',
    'South Africa',
    'Kenya',
    'Ghana',
    'Morocco',
    'Colombia',
    'Chile',
    'Egypt',
    'Turkey',
    'Saudi Arabia',
    'Poland',
    'Norway',
    'Switzerland',
    'Thailand',
    'Malaysia',
    'Indonesia',
    'Vietnam',
    'Pakistan',
    'Bangladesh',
    'Ukraine',
    'Greece',
    'New Zealand',
    'Israel',
    'Austria',
    'Hungary',
    'Czech Republic',
]
