export const DEFAULT_PASSWORD = 'password'
export const SALT_ROUNDS = 10
export const countries = [
    'US',
    'Canada',
    'UK',
    'Australia',
    'France',
    'Germany',
    'Japan',
    'China',
    'India',
    'Brazil',
    'Russia',
    'Italy',
    'Spain',
    'Mexico',
    'South Korea',
    'Netherlands',
    'Sweden',
    'Nigeria',
    'Argentina',
    'Singapore',
    'Philippines',
    'Belgium',
    'Portugal',
    'Denmark',
    'Finland',
    'Ireland',
    'South Africa',
    'Kenya',
    'Ghana',
    'Morocco',
    'Colombia',
    'Chile',
    'Egypt',
    'Turkey',
    'Saudi Arabia',
    'Poland',
    'Norway',
    'Switzerland',
    'Thailand',
    'Malaysia',
    'Indonesia',
    'Vietnam',
    'Pakistan',
    'Bangladesh',
    'Ukraine',
    'Greece',
    'New Zealand',
    'Israel',
    'Austria',
    'Hungary',
    'Czech Republic',
]
